export type Service = { title: string; description: string; problem: string; benefits: string[]; audience: string };
export const services: Service[] = [
  { title: "Gestão de Tráfego Pago", description: "Planejamento, configuração, acompanhamento e otimização de campanhas em plataformas como Meta Ads e Google Ads.",
    problem: "Investir em anúncios sem acompanhamento gera cliques sem direção e dificulta entender o que está trazendo oportunidades.",
    benefits: ["Campanhas alinhadas ao objetivo comercial", "Acompanhamento de investimento, cliques, leads e CPL", "Relatórios dentro do portal do cliente"],
    audience: "Empresas que querem gerar novas oportunidades com mídia paga e acompanhar os indicadores." },
  { title: "Landing Pages", description: "Páginas focadas em uma única oferta ou campanha, desenhadas para captar contatos e receber tráfego pago.",
    problem: "Anúncios que enviam o visitante para uma página genérica desperdiçam parte do investimento.",
    benefits: ["Mensagem direta e objetiva", "Formulário conectado ao CRM", "Carregamento rápido e layout responsivo"],
    audience: "Negócios que anunciam ou lançam ofertas e querem gerar leads." },
  { title: "Sites Institucionais", description: "Sites profissionais que apresentam sua empresa, seus serviços e seus canais de contato com clareza.",
    problem: "Empresas sem site, ou com um site desatualizado, perdem credibilidade e deixam de aproveitar melhor o tráfego.",
    benefits: ["Presença profissional na internet", "Layout responsivo para celular", "Estrutura pronta para campanhas e Google"],
    audience: "Empresas que precisam de uma vitrine digital confiável." },
  { title: "Desenvolvimento Web", description: "Sistemas, painéis e aplicações web sob medida para organizar a operação da sua empresa.",
    problem: "Planilhas e processos manuais atrapalham o crescimento e geram retrabalho.",
    benefits: ["Solução feita para o seu processo", "Acesso com login e permissões", "Base pronta para evoluir"],
    audience: "Empresas que precisam de uma ferramenta própria, além de um site." },
  { title: "Automações", description: "Integração entre formulários, WhatsApp, e-mail e outras ferramentas para automatizar tarefas repetitivas.",
    problem: "Atendimento e follow-up feitos à mão são lentos e deixam contatos sem resposta.",
    benefits: ["Menos tarefas manuais", "Resposta mais rápida aos contatos", "Processo comercial organizado"],
    audience: "Equipes que perdem tempo com tarefas repetitivas." },
  { title: "Criativos", description: "Peças visuais para anúncios e redes sociais, alinhadas à identidade da sua marca e ao objetivo da campanha.",
    problem: "Materiais sem padrão visual enfraquecem a marca e reduzem a atenção do público.",
    benefits: ["Identidade visual consistente", "Formatos para cada canal", "Foco na mensagem da campanha"],
    audience: "Marcas que anunciam ou publicam com frequência." },
  { title: "Copywriting", description: "Textos estratégicos para páginas, anúncios, ofertas e comunicação comercial.",
    problem: "Uma boa oferta mal explicada não convence quem está decidindo.",
    benefits: ["Mensagem clara e persuasiva", "Textos adaptados ao público", "Chamadas para ação objetivas"],
    audience: "Empresas que querem comunicar melhor o que vendem." },
  { title: "Consultoria Digital", description: "Análise da presença digital atual e um plano prático de melhorias.",
    problem: "Sem diagnóstico, é difícil saber por onde começar e o que priorizar.",
    benefits: ["Visão clara dos pontos de melhoria", "Prioridades definidas", "Plano de ação realista"],
    audience: "Empresas que querem se estruturar digitalmente, mas não sabem por onde começar." },
];
